name: ROS2 CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.7.13
        with:
          required-ros-distributions: rolling

      - name: Install Additional Packages
        run: |
          pip install -U catkin_pkg colcon-common-extensions colcon-meson
        shell: powershell

      - name: Clone repos
        run: vcs import src --input https://gist.githubusercontent.com/ahcorde/10ae278905fe15414ef02b5a4c9de2f6/raw/f707b68267eb0bd419d3f1f0d940cabca531292c/ros2.repos

      - name: Build ROS 2 workspace
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          colcon build --merge-install --packages-skip rosidl_rust


  # lint:
  #   name: ament_${{ matrix.linter }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #         linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
  #   steps:
  #     - 
  #       name: Checkout code
  #       uses: actions/checkout@v4
  #     -
  #       name: Run linter
  #       uses: ./.github/actions/lint/
  #       env: 
  #         LINTER: ${{ matrix.linter }}
